{{- range $key, $value := .Values.awsSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Values.fullnameOverride }}-{{ $key }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: {{ $key }}
  data:
  {{- range $refs := $value}}
  - secretKey: {{ $refs }}
    remoteRef:
      key: {{ $key }}
      property: {{ $refs }}
  {{- end }}
---
{{- end }}