apiVersion: v1
kind: Service
metadata:
  name: {{ include "whisperchain-frontend.fullname" . }}
  labels:
    {{- include "whisperchain-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "whisperchain-frontend.selectorLabels" . | nindent 4 }}

---
{{- if .Values.frontendProxy.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendProxy.service.name}}
spec:
  type: ExternalName
  externalName: {{ .Values.frontendProxy.domainName}}
{{- end }}
