name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Enter github branch name to be deployed'
        required: true
        default: 'main'
      description:
        description: 'Enter description about deployment'
        required: true
        default: 'New feature release'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: us-west1
  GKE_CLUSTER: plg
  GKE_ZONE: us-west1
  DEPLOYMENT_NAME: whisper-chain-be
  REPOSITORY: plg-web3
  IMAGE: whisper-chain-be

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: actions/checkout@v2
        with:
          repository: "WhisperChain/dev.secrets"
          ref: "main"
          token: ${{ secrets.PAT }}
          path: "secrets"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build and push image
        env:
          ENV: "prod"
          URL: "us-west1-docker.pkg.dev/plg-web3/whisperchain-staging/whisper-chain-be"
          TAG: ${{ github.run_id }}-${{ github.run_attempt }}
        run: |-
          mv secrets/backend.staging.env .env 
          docker build --tag "$URL:$TAG" --build-arg ENV="$ENV" .
          gcloud auth configure-docker us-west1-docker.pkg.dev --quiet --project plg-web3
          docker push "$URL:$TAG"

      - name: Set up GKE credentials
        run: |-
          gcloud components install gke-gcloud-auth-plugin --quiet
          gcloud container clusters get-credentials plg --region us-west1 --project plg-web3

      - name: "Deploy to Kubernetes"
        id: deploy-eks
        env:
          URL: "us-west1-docker.pkg.dev/plg-web3/whisperchain-staging/whisper-chain-be"
          TAG: ${{ github.run_id }}-${{ github.run_attempt }}
        run: |-
          helm upgrade --install \
          --set image.repository=${URL} \
          --set image.tag=${TAG} \
          --values ./kubernetes-values/staging.yaml \
          whisper-chain-be ./helm
